# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos-6.2-x86_64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on its network, but cannot be accessed (through this
  # network interface) by any external networks.
  # config.vm.network :hostonly, "192.168.33.10"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as a
  # physical device on your network.
  #config.vm.network :bridged

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port 22, 2222
  config.vm.forward_port 80, 18081

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"
  #config.vm.share_folder "v-django", "/srv/rainmap/django", "../../src/django"
  #config.vm.share_folder "v-public", "/srv/rainmap/public", "../../src/public"

  # Enable provisioning with Puppet stand alone.
  config.vm.provision :puppet,
                      # :pp_path = "/tmp/vagrant-puppet",
                      :module_path => "../puppet/modules/" do |puppet|
    puppet.manifests_path = "../puppet/"
    puppet.manifest_file = "site.pp"
  end
end
